os:
  - linux
  - osx
  - windows

sudo: false

language: go

go:
  - "1.13"

install:
  - go get "github.com/go-sql-driver/mysql"

script:
  - go build -o mysql_markdown mysql_markdown.go
  - chmod +x mysql_markdown
  - ./mysql_markdown -h

branches:
  only:
  - master

notifications:
  email: true
